Ability to definied a custom Template class
ahmedaljazzar/django-mako pull request #4
Opened 2017-12-06 18:56 UTC by WnP

This is an alternative fix for #3 which IMHO is preferable.

Let me know your through

2017-12-08 12:35 UTC, iamjazzar requested changes
Thanks for your contribution, just one minor comment.

2017-12-08 12:35 UTC, ahmedaljazzar commented on djangomako/backends.py
> +        self.Template = import_string(options.pop(
Can you rename this to `template_class` instead of `Template`?

2017-12-08 15:30 UTC, WnP commented
@ahmedaljazzar sure, no problem, sounds a good choice

2017-12-08 16:10 UTC, iamjazzar approved these changes

2017-12-08 16:10 UTC, ahmedaljazzar commented
Thanks for your contribution @WnP :D

2017-12-08 16:10 UTC, merged

2017-12-15 16:25 UTC, WnP commented
@ahmedaljazzar you're welcome :wink: 

Any chance to release a version with this fix on pypi?

2017-12-28 17:10 UTC, ahmedaljazzar commented
Released, just check `django-mako v1.1.0`